blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/aniasse/thymus/discussions
    about: Pour les questions générales et idées, utilisez les Discussions.
